project_name: rnssh
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: rnssh
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto

# https://goreleaser.com/customization/changelog/
# disabled auto create changelog from commit message.
changelog:
  skip: true

# homebrew
brews:
  - description: "Easy ssh to EC2"
    repository:
      owner: reiki4040
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    homepage: "https://github.com/reiki4040/rnssh"
    install: |
      bin.install "rnssh"
    caveats: |
      # rnssh need AWS access key for working.
      # Please set key/secret to AWS credentials (~/.aws/credentials)

      [default]
      aws_access_key_id=your_key_id
      aws_secret_access_key=your_secret

      # or environment variable for AWS connection.
      # (~/.bashrc, ~/.zshrc or other.)

      export AWS_ACCESS_KEY_ID=YOUR_AWS_ACCESS_KEY
      export AWS_SECRET_ACCESS_KEY=YOUR_AWS_SECRET_ACCESS_KEY

      # set default aws region.
      rnssh -init

    #custom_block: # later use for devel version